<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<html>
<head>
    <title>memberCreate</title>
    <link href="../../css/style.css" rel="stylesheet" type="text/css" />
<style>
</style>
</head>

<body>
  <div class="main">
    <form:form method="post" action="processAgent" modelAttribute="memberCreateForm">
      <input type="hidden" name="${_csrf.parameterName}"  value="${_csrf.token}" />

    <h2 style="color:${currUser.role.color}">${currUser.role.desc}&nbsp; ${currUser.contact} - Create ${currCreateRole.desc}:</h2>
    <table border="0" cellpadding="3" cellspacing="0" width="500">
    <tbody align="left" style="color:purple; background-color:${currCreateRole.color}">
    <tr>
    <td width="30%"><font color="#333" size="2">Email (Logon Username)*:</font></td>
    <td width="70%"><input type="text" style='width:20em' name="profile.email" value="${memberCreateForm.inCompleteProfile.email}"/></td>
    </tr>
    <tr>
    <td width="30%"><font color="#333" size="2">Contact*:</font></td>
    <td width="70%"><input type="text" name="profile.contact" value="${memberCreateForm.inCompleteProfile.contact}" /></td>
    </tr>
    <c:if test="${currCreateRole.shortCode == 'Player'}">
      <tr>
      <td width="30%"><font color="#333" size="2">Nick Name*:</font></td>
      <td width="70%"><input type="text" name="profile.nickname" value="${memberCreateForm.inCompleteProfile.nickname}" /></td>
      </tr>
    </c:if>
    <tr>
    <td width="30%"><font color="#333" size="2">Phone*:</font></td>
    <td width="70%"><input type="text" name="profile.phone" value="${memberCreateForm.inCompleteProfile.phone}"/></td>
    </tr>
    </tbody>
    </table>
    <br/>
    <tr><td><font color="#aaa" size="2">*required field</font></td></tr>
    <br/>
    <tr><td><font color="red" size="3">${memberCreateForm.errMsg}</font></td></tr>
    <br/>
    <br/>
    <tr>
    <font color="#aaa" size="2">(Password will be autogenerated and emailed to the ${currCreateRole.desc})</font>
    </tr>
    </br>
    </br>
    <table border="0" cellpadding="3" cellspacing="0" width="600">
    <tbody align="left" style="color:purple;">
    </br>
    <tr>
    <td><input type="submit" name="memberSave" value="Create" class="button" style="height:23px;"/></td>
    <td><input type="submit" name="memberCancel" value="Cancel" class="button" style="height:23px; background-color:red;"/></td>
    </tr>
    </tbody>
    </table>
    </form:form>
  </div>

</body>
</html>
